# Generated by Django 5.2.6 on 2025-09-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_intent_degree_quiz_intent_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='intent_degree',
            field=models.CharField(blank=True, choices=[('btech', 'BTech (4 years)'), ('mtech', 'MTech (2 years)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='intent_semester',
            field=models.CharField(blank=True, choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8'), ('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4')], max_length=2, null=True),
        ),
    ]
