apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: hello-k8s
build:
  artifacts:
    - image: hello-service
      context: services/hello
    - image: world-service
      context: services/world
    - image: gateway-service
      context: gateway
  local:
    push: false
manifests:
  rawYaml:
    - k8s/hello-deployment.yaml
    - k8s/world-deployment.yaml
    - k8s/gateway-deployment.yaml
    - k8s/hello-configmap.yaml
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: gateway-service
    port: 80       # service port in cluster
    localPort: 8080  # port on your laptop
