apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: users-api
build:
  local:
    push: false
  artifacts:
    - image: users-api
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl: {}

manifests:
  rawYaml:
    - k8s/*.yaml
    
portForward:
  - resourceType: service
    resourceName: users-api
    port: 8000
    localPort: 8000
