# Generated by Django 5.2.6 on 2025-09-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_degree_userprofile_year_of_admission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='student_id',
        ),
    ]
